apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: nemo260/doc-doc-fe
  newName: nemo260/doc-doc-fe
  newTag: 1.0.11
- name: nemo260/doc-doc-webapi
  newName: nemo260/doc-doc-webapi
  newTag: 1.1.0

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: mne-doc-doc-fe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  mne-doc-doc-fe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1