apiVersion: apps/v1
kind: Deployment
metadata:
  name: mne-doc-doc-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /mne-openapi
            - name: BASE_URL
              value: /mne-openapi-ui