apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: nemo260/doc-doc-fe 
  newName: nemo260/doc-doc-fe # {"$imagepolicy":  "wac-hospital:doc-doc-fe:name"}
  newTag: main # {"$imagepolicy": "wac-hospital:doc-doc-fe:tag"}
