apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
 app.kubernetes.io/part-of: wac-hospital
 app.kubernetes.io/name: mne-doc-doc

resources:
 - ../../../apps/mne-doc-doc-fe
 - ../../../apps/mne-doc-doc-webapi

components:
 - ../../../components/version-release